const registeredProxy = [
   {
      accountNumber: 1425363,
      fullName: "ABDULSALAMI ABDULRAHMAN",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "25",
   },
   {
      accountNumber: 1425363,
      fullName: "CHUKWUKWA NWAFOR",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "342",
   },
   {
      accountNumber: 1425363,
      fullName: "ANTHONY ENENCHE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "1,234",
   },
   {
      accountNumber: 1425363,
      fullName: "OGHENEFEGIRO ONORIODE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "3,829",
   },
   {
      accountNumber: 1425363,
      fullName: "MASON MOUNT",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "14",
   },
   {
      accountNumber: 1425363,
      fullName: "OLADIPO ADEWALE OLUMIDE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "200",
   },
   {
      accountNumber: 1425363,
      fullName: "KOLADE FRIDAY BABALOLA",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "20,193",
   },
   {
      accountNumber: 1425383,
      fullName: "RUKEVWE OCHUKO",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "20,193",
   },
   {
      accountNumber: 1425363,
      fullName: "ABDULSALAMI ABDULRAHMAN",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "25",
   },
   {
      accountNumber: 1425363,
      fullName: "CHUKWUKWA NWAFOR",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "342",
   },
   {
      accountNumber: 1425363,
      fullName: "ANTHONY ENENCHE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "1,234",
   },
   {
      accountNumber: 1425363,
      fullName: "OGHENEFEGIRO ONORIODE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "3,829",
   },
   {
      accountNumber: 1425363,
      fullName: "MASON MOUNT",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "14",
   },
   {
      accountNumber: 1425363,
      fullName: "OLADIPO ADEWALE OLUMIDE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "200",
   },
   {
      accountNumber: 1425363,
      fullName: "KOLADE FRIDAY BABALOLA",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "20,193",
   },
   {
      accountNumber: 1425363,
      fullName: "ABDULSALAMI ABDULRAHMAN",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "25",
   },
   {
      accountNumber: 1425363,
      fullName: "CHUKWUKWA NWAFOR",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "342",
   },
   {
      accountNumber: 1425363,
      fullName: "ANTHONY ENENCHE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "1,234",
   },
   {
      accountNumber: 1425363,
      fullName: "OGHENEFEGIRO ONORIODE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "3,829",
   },
   {
      accountNumber: 1425363,
      fullName: "MASON MOUNT",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "14",
   },
   {
      accountNumber: 1425363,
      fullName: "OLADIPO ADEWALE OLUMIDE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "200",
   },
   {
      accountNumber: 1425363,
      fullName: "KOLADE FRIDAY BABALOLA",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "20,193",
   },
   {
      accountNumber: 1425363,
      fullName: "ABDULSALAMI ABDULRAHMAN",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "25",
   },
   {
      accountNumber: 1425363,
      fullName: "CHUKWUKWA NWAFOR",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "342",
   },
   {
      accountNumber: 1425363,
      fullName: "ANTHONY ENENCHE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "1,234",
   },
   {
      accountNumber: 1425363,
      fullName: "OGHENEFEGIRO ONORIODE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "3,829",
   },
   {
      accountNumber: 1425363,
      fullName: "MASON MOUNT",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "14",
   },
   {
      accountNumber: 1425363,
      fullName: "OLADIPO ADEWALE OLUMIDE",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "200",
   },
   {
      accountNumber: 1425363,
      fullName: "KOLADE FRIDAY BABALOLA",
      proxyName: "MR MATTHEW AKINLADE",
      holdings: "20,193",
   },
];

export default registeredProxy